{"name": "Логин с неверными credentials", "status": "passed", "description": "Тест логина с неверными учетными данными", "steps": [{"name": "Отправка запроса с неверными данными", "status": "passed", "start": 1756924176949, "stop": 1756924177038}, {"name": "Проверка ошибки авторизации", "status": "passed", "start": 1756924177038, "stop": 1756924177038}], "parameters": [{"name": "invalid_data", "value": "{'email': 'nonexistent@test.com', 'password': 'wrongpassword'}"}], "start": 1756924176949, "stop": 1756924177040, "uuid": "639b3ded-a9da-48ef-91ad-fce4a06d642b", "historyId": "e5f6a9c9f77514e355c411d0a2643ee6", "testCaseId": "9329ecf4e8dae93c2ec48d7631be1618", "fullName": "tests.test_login_user.TestLoginUser#test_login_invalid_credentials_fails", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "RUMSKLCG1160Z8S"}, {"name": "thread", "value": "11304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}